modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="farmerscuttingeverything"
version="${file.jarVersion}"
displayName="Farmer's Cutting Everything"
authors="Chaolux"
description=''''''
[[dependencies.farmerscuttingeverything]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmerscuttingeverything]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmerscuttingeverything]]
modId = "farmersdelight"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"